virtualenv:
  system_site_packages: true
language: python
python:
  - "2.7"
before_install: /bin/bash before_install.sh
install: /bin/bash install.sh
script: cd ..; PYTHONPATH=. python grr/run_tests.py
